### ISSUE TITLE
Copy Link for template in designer does not work

### ISSUE THREAD

**Issue by annhat-ux** [ideaconsult/templateforge#33]
https://enanomapper.adma.ai/templates?uuid=d96eb495-7977-468f-a926-16789ed7ecb2

Above link returns 404 for me.

UUID: d96eb495-7977-468f-a926-16789ed7ecb2

**Comment by vedina** [comment]
the link should have been https://enanomapper.adma.ai/templates/?uuid=d96eb495-7977-468f-a926-16789ed7ecb2  (note the slash)

**Comment by kerberizer** [comment]
Fixed. It works now both ways (will automatically redirect to the URL with the `/`). Thank you very much @annhat-ux!

**Comment by annhat-ux** [comment]
I clicked the link, it worked. I clicked the logo of the designer on the left top corner to go back to the list of templates and now the cytokine template is nulled out. Is there a way to retrieve what I filled in before? This is a big bug.

**Comment by kerberizer** [comment]
> I clicked the link, it worked. I clicked the logo of the designer on the left top corner to go back to the list of templates and now the cytokine template is nulled out. Is there a way to retrieve what I filled in before? This is a big bug.

That's now tracked in #34
