### ISSUE TITLE
Drafts destroyed when opened for editing and immediately saved

### ISSUE THREAD

**Issue by kerberizer** [ideaconsult/templateforge#34]
Per title. Steps to reproduce:
1. create a new draft or copy existing one
2. select the draft from the main page and click "Edit blueprint"
3. on the next page—the "Welcome" step—immediately click "Save"
4. get back to the main page by, e.g., clicking the top left link
5. the draft is now shown with `?` in all columns

Notes:
* The problem does not happen if "Next" is clicked on the "Welcome" page, **even if** "Save" has already been clicked.
* Looking at the requests in the browser dev tools, the "Save" button on the "Welcome" page sends a POST with a mostly empty JSON. Clicking "Next" on this page seems to send the correct JSON. This likely explains the previous bullet.
* This problem has been observed on the `main` branch, deployed on https://enanomapper.adma.ai/templates (https://enm-test.adma.ai/templates has been deployed with the same config for safe testing).
* The goal is to have this fixed on `develop`.

CC @vedina

**Comment by vedina** [comment]
Can we have Selenium test for this issue? 
Perhaps first start with the test and then fix and be sure it is fixed @sergesoroka

**Comment by vedina** [comment]
> the "Save" button on the "Welcome" page sends a POST with a mostly empty JSON

That should be the default JSON - same as if one starts a brand new template.  This likely means the React app has not assigned the variable which is used by the POST and sends some default value. (just a guess).
